### ISSUE TITLE
Setup regular training on Git and Github

### ISSUE THREAD

**Issue by akouete-kpakpo** [ML-for-B-E/nevergrad#11]
## Context
Ideally 2 times a week, every 3 day, a session of 1 hour.

Suggestions for the content of a session:
- how to commit using Vscode extension. cf https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens

**Comment by abiolaTresor** [comment]
Hello guys, this is the list of the Github discussions we will be having with @Ethel2003 the next few days:

- MR
- Solving conflicts
- Issues
- utiliser l’interface graphique de git dans VSCode/ GitHub desktop

@akouete-kpakpo  @Ethel2003  any comment before we suggest the times when the discussions may take place?

**Comment by akouete-kpakpo** [comment]
@abiolaTresor the planning seems good to me. Except the last topic:

utiliser l’interface graphique de git dans VSCode ~/ GitHub desktop~

@Ethel2003 works in Vscode. I think we should focus on Vscode only.

**Comment by akouete-kpakpo** [comment]
@abiolaTresor also please start the training as soon as possible. We have already wasted 1 week since this issue was created. 2 training sessions could have been given.

**Comment by akouete-kpakpo** [comment]
@abiolaTresor @chrichri17 it seems this issue is over? If so could you close?
