### ISSUE TITLE
Write the ouputs of an experiment in a folder `outputs`

### ISSUE THREAD

**Issue by akouete-kpakpo** [ML-for-B-E/nevergrad#13]
## Context
The outputs of an experiment are written at the root of the project. In addition, they are not ignored by git.

## Solution proposed
Write the outputs in a folder `outputs` at the root of the project

**Comment by akouete-kpakpo** [comment]
@chrichri17 @abiolaTresor @Ethel2003 
please I'm adding this section 

> Also use
> 
> python -m nevergrad.benchmark rice_irrigation --output=outputs/2/ --num_workers=4 --plot
> --plot to output plots
> --output=_ to generate outputs in a specific folder
> --num_workers=_ to parallelize the job on multiple cores

in the wiki https://github.com/akouete-kpakpo/nevergrad/wiki/Installation. 

Could you review please? If ok, I will close this issue

**Comment by chrichri17** [comment]
Looks good @akouete-kpakpo

**Comment by akouete-kpakpo** [comment]
thanks @chrichri17 

small change on the wiki. The right command is
`python -m nevergrad.benchmark rice_irrigation --output=outputs/2/rice_irrigation.csv --num_workers=4 --plot`

**Comment by akouete-kpakpo** [comment]
@chrichri17 I'm reopening as I noticed that the command does not work if the folder does not exists
