### ISSUE TITLE
Run a first experiment of irrigation planning for a sugarbeet crop in Porto-Novo

### ISSUE THREAD

**Issue by akouete-kpakpo** [ML-for-B-E/nevergrad#33]

**Comment by akouete-kpakpo** [comment]
I have this plot for the variety 601 of sugarbeet crop

![image](https://user-images.githubusercontent.com/26568112/182020717-1ed7ceda-36b1-46b2-a740-7626217d1c9e.png)

Unsatisfying as:
- insensitivity to irrigation event date: when I change date of month for the only irrigation event, I have exactly the same plot, the difference between the 2 plots should start at event date with a lag, intuitively
- insensitivity to water volume: when I change the water volume from 0.01 cm to 10 cm, I have exactly the same plot
- I don't have the same level of leaf area index as in Allard's tuto: my LAI ranges in 0 - 0.2 whereas his lies in 0-7

![image](https://user-images.githubusercontent.com/26568112/182020820-a158943a-1b97-4e12-9f40-e862d32cf0cf.png)

![image](https://user-images.githubusercontent.com/26568112/182020881-2232a47f-2502-4d7c-88da-ae273c9046d3.png)

Have to understand why

**Comment by Ethel2003** [comment]
When i did my first simulation of sugarbeet based on the notebook of Allard I have the same level of leaf area index as Allard. I could say the fact that you don't have the same thing as Allard is due to the parameters of crop.

**Comment by akouete-kpakpo** [comment]
thanks for your suggestion @Ethel2003 . Indeed, my previous plot shows a sugarbeet simulation in Lome. But in Allard's tuto, the crop locates in Wageningen, Netherlands. This is what I have by fixing the location: now I have the same range of values for the leaf area index as in the tuto notebook

![image](https://user-images.githubusercontent.com/26568112/182246240-08a8e3d5-367d-4006-b5d3-182fb04ca477.png)

**Comment by akouete-kpakpo** [comment]
The difference is explained by the rain intensity during the crop (source of data plotted: NASA Power database)

## Lome, Togo
![image](https://user-images.githubusercontent.com/26568112/182247043-f0490638-2249-4464-b9bd-ae44b6e013bf.png)

## Wageningen, Netherlands
![image](https://user-images.githubusercontent.com/26568112/182246924-f53fe9d7-3387-4180-8e93-ced9e11875ea.png)

**Comment by akouete-kpakpo** [comment]
I think that 

## root zone soil moisture

![image](https://user-images.githubusercontent.com/26568112/182252019-ee0151ed-c7e4-4151-96ac-29ece2751bab.png)

 is more explicit than

## Leaf area index

![image](https://user-images.githubusercontent.com/26568112/182252059-f35b5c26-b459-4a46-ac71-0c4a252eea8e.png)

to correlate crop ecosystem evolution with irrigation events

**Comment by Ethel2003** [comment]
Okay. It is more comprehensible

**Comment by akouete-kpakpo** [comment]
solved in #36 

it was a config bug. Now all good

![image](https://user-images.githubusercontent.com/26568112/183421226-9653ca27-38f9-44a9-9c48-b254036ed37e.png)
